services:
  postgres:
    image: postgres:16
    container_name: case-postgres
    environment:
      POSTGRES_DB: case_db
      POSTGRES_USER: case_user
      POSTGRES_PASSWORD: case_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: case-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
